// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyacdeqkjnolzojqgpxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5YWNkZXFram5vbHpvanFncHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjgxMzcsImV4cCI6MjA2NDcwNDEzN30.uLfCoo9hQRCu3QJYHAmWmxVbhCBX7z8JtabbnupIAk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);